sonar.projectKey=flashcard-app
sonar.projectName=Flashcard App
sonar.projectVersion=1.0

sonar.sources=backend/src/main,frontend/src
sonar.tests=backend/src/test
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.test.ts,**/*.test.tsx

sonar.java.binaries=backend/target/classes
sonar.java.libraries=backend/target/dependency/*.jar
sonar.java.source=17
sonar.junit.reportPaths=backend/target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml

sonar.javascript.lcov.reportPaths=frontend/coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/build/**,**/target/**,**/dist/**,frontend/public/**

# Create a token and add it as user environment variable in windows
# and name the variable SONAR_TOKEN
# Run with:
# mvn clean verify sonar:sonar "-Dsonar.projectKey=flashcard-backend" "-Dsonar.token=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"