sonar.projectKey=flashcard-app
sonar.projectName=Flashcard App
sonar.projectVersion=1.0

sonar.sources=src/main
sonar.tests=src/test

sonar.java.binaries=target/classes
sonar.java.libraries=target/dependency/*.jar
sonar.java.source=17
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

sonar.exclusions=**/target/**

# Create a token and add it as user environment variable in windows
# and name the variable SONAR_TOKEN
# Run with:
# mvn clean verify sonar:sonar "-Dsonar.projectKey=flashcard-backend" "-Dsonar.token=$env:SONAR_TOKEN" "-Dsonar.host.url=http://localhost:9000"